# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mapreduce_pb2 as mapreduce__pb2


class CoordinatorStub(object):
    """Coordinator Service - handles job submission and status
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/mapreduce.Coordinator/SubmitJob',
                request_serializer=mapreduce__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.SubmitJobResponse.FromString,
                )
        self.GetJobStatus = channel.unary_unary(
                '/mapreduce.Coordinator/GetJobStatus',
                request_serializer=mapreduce__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.GetJobStatusResponse.FromString,
                )
        self.GetTask = channel.unary_unary(
                '/mapreduce.Coordinator/GetTask',
                request_serializer=mapreduce__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.GetTaskResponse.FromString,
                )
        self.ReportTaskComplete = channel.unary_unary(
                '/mapreduce.Coordinator/ReportTaskComplete',
                request_serializer=mapreduce__pb2.ReportTaskCompleteRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.ReportTaskCompleteResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/mapreduce.Coordinator/Heartbeat',
                request_serializer=mapreduce__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.HeartbeatResponse.FromString,
                )


class CoordinatorServicer(object):
    """Coordinator Service - handles job submission and status
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTaskComplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=mapreduce__pb2.SubmitJobRequest.FromString,
                    response_serializer=mapreduce__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=mapreduce__pb2.GetJobStatusRequest.FromString,
                    response_serializer=mapreduce__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=mapreduce__pb2.GetTaskRequest.FromString,
                    response_serializer=mapreduce__pb2.GetTaskResponse.SerializeToString,
            ),
            'ReportTaskComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTaskComplete,
                    request_deserializer=mapreduce__pb2.ReportTaskCompleteRequest.FromString,
                    response_serializer=mapreduce__pb2.ReportTaskCompleteResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mapreduce__pb2.HeartbeatRequest.FromString,
                    response_serializer=mapreduce__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.Coordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Coordinator(object):
    """Coordinator Service - handles job submission and status
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.Coordinator/SubmitJob',
            mapreduce__pb2.SubmitJobRequest.SerializeToString,
            mapreduce__pb2.SubmitJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.Coordinator/GetJobStatus',
            mapreduce__pb2.GetJobStatusRequest.SerializeToString,
            mapreduce__pb2.GetJobStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.Coordinator/GetTask',
            mapreduce__pb2.GetTaskRequest.SerializeToString,
            mapreduce__pb2.GetTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTaskComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.Coordinator/ReportTaskComplete',
            mapreduce__pb2.ReportTaskCompleteRequest.SerializeToString,
            mapreduce__pb2.ReportTaskCompleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mapreduce.Coordinator/Heartbeat',
            mapreduce__pb2.HeartbeatRequest.SerializeToString,
            mapreduce__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
